//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.usertasks = new HashSet<usertask>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string CategoryName { get; set; }
        public int Priority { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<usertask> usertasks { get; set; }
    }
}
